name: Renovate

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: renovatebot/github-action@v41.0.2
        with:
          configurationFile: renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
